package View.imagens.telas;


import javax.swing.JFrame;

public class MenuPrincipal extends JFrame {

    

    public MenuPrincipal() {
        initComponents();
        setTitle("Tela de Cadastros - Distribuidora de Água");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButtonCadastroClientes = new javax.swing.JButton();
        jButtonCadastroFuncionarios = new javax.swing.JButton();
        jButtonCadastroProduto = new javax.swing.JButton();
        jButtonCadastroVenda = new javax.swing.JButton();
        jButtonCadastroFornecedor = new javax.swing.JButton();
        jButtonVoltar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(232, 232, 232));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Menu", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 18), new java.awt.Color(0, 51, 153))); // NOI18N
        jPanel1.setForeground(new java.awt.Color(0, 153, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonCadastroClientes.setBackground(new java.awt.Color(86, 203, 238));
        jButtonCadastroClientes.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        jButtonCadastroClientes.setForeground(new java.awt.Color(255, 255, 255));
        jButtonCadastroClientes.setText("Cadastro de Clientes");
        jButtonCadastroClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadastroClientesActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonCadastroClientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 150, 280, 40));

        jButtonCadastroFuncionarios.setBackground(new java.awt.Color(86, 203, 238));
        jButtonCadastroFuncionarios.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        jButtonCadastroFuncionarios.setForeground(new java.awt.Color(255, 255, 255));
        jButtonCadastroFuncionarios.setText("Cadastro de Funcionários");
        jButtonCadastroFuncionarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadastroFuncionariosActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonCadastroFuncionarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 310, 280, 40));

        jButtonCadastroProduto.setBackground(new java.awt.Color(86, 203, 238));
        jButtonCadastroProduto.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        jButtonCadastroProduto.setForeground(new java.awt.Color(255, 255, 255));
        jButtonCadastroProduto.setText("Cadastro de Produtos");
        jButtonCadastroProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadastroProdutoActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonCadastroProduto, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 390, 280, 40));

        jButtonCadastroVenda.setBackground(new java.awt.Color(86, 203, 238));
        jButtonCadastroVenda.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        jButtonCadastroVenda.setForeground(new java.awt.Color(255, 255, 255));
        jButtonCadastroVenda.setText("Cadastro de Vendas");
        jButtonCadastroVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadastroVendaActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonCadastroVenda, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 470, 280, 40));

        jButtonCadastroFornecedor.setBackground(new java.awt.Color(86, 203, 238));
        jButtonCadastroFornecedor.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        jButtonCadastroFornecedor.setForeground(new java.awt.Color(255, 255, 255));
        jButtonCadastroFornecedor.setText("Cadastro de Fornecedor");
        jButtonCadastroFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadastroFornecedorActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonCadastroFornecedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 230, 280, 40));

        jButtonVoltar.setBackground(new java.awt.Color(86, 203, 238));
        jButtonVoltar.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        jButtonVoltar.setForeground(new java.awt.Color(255, 255, 255));
        jButtonVoltar.setText("Voltar");
        jButtonVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVoltarActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonVoltar, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 570, 130, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/imagens/telas/tela menu.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 1000, 620));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1063, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 671, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCadastroFuncionariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadastroFuncionariosActionPerformed
        CadastroFuncionarios telaFuncionarios = new CadastroFuncionarios();
        telaFuncionarios.setVisible(true);
    
    }//GEN-LAST:event_jButtonCadastroFuncionariosActionPerformed

    private void jButtonCadastroClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadastroClientesActionPerformed
        CadastroClientes telaCliente = new CadastroClientes();
        telaCliente.setVisible(true);
    }//GEN-LAST:event_jButtonCadastroClientesActionPerformed

    private void jButtonCadastroProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadastroProdutoActionPerformed
        CadastroProdutos telaProdutos = new CadastroProdutos();
        telaProdutos.setVisible(true);
    }//GEN-LAST:event_jButtonCadastroProdutoActionPerformed

    private void jButtonCadastroVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadastroVendaActionPerformed
        CadastroVenda telaVenda = new CadastroVenda();
        telaVenda.setVisible(true);
    }//GEN-LAST:event_jButtonCadastroVendaActionPerformed

    private void jButtonCadastroFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadastroFornecedorActionPerformed
        CadastroFornecedor telaFornecedor = new CadastroFornecedor();
        telaFornecedor.setVisible(true);
    }//GEN-LAST:event_jButtonCadastroFornecedorActionPerformed

    private void jButtonVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVoltarActionPerformed
         Login login = new Login();
        login.setVisible(true);
        this.dispose(); 
    }//GEN-LAST:event_jButtonVoltarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>
  
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new MenuPrincipal().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCadastroClientes;
    private javax.swing.JButton jButtonCadastroFornecedor;
    private javax.swing.JButton jButtonCadastroFuncionarios;
    private javax.swing.JButton jButtonCadastroProduto;
    private javax.swing.JButton jButtonCadastroVenda;
    private javax.swing.JButton jButtonVoltar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
